### PR TITLE
011

### PR DESCRIPTION
**Pull request by zoranzaric**
Shownotes for episode 11

### CODE REVIEW

**Comment by bstrie** [comment]
I'll also listen through it to add the more detailed timestamps like we usually have. @zoranzaric , mind if I submit that PR to this branch of yours?

**Comment by bstrie** [comment]
I wasn't able to push to this specific branch so I've continued the PR over in https://github.com/rustacean-station/rustacean-station.org/pull/28 .

**Comment by zoranzaric** [comment]
Sorry @bstrie just saw the comment :(

**Comment by bstrie** [comment]
No worries. :)

**Pull request closed without merging**
