### PR TITLE
add episode 009 transcript

### PR DESCRIPTION
**Pull request by ericseppanen**
Some of the formatting is a little tricky in this second interview.  I
think that most of the time, they're talking about projects (i.e. Tonic,
Tower) but I have used `tonic` and `tower` when we're talking about the
crates.

It's quite ambiguous, but I'm trying to not have sentences where every
third word is in `code` backticks.

### CODE REVIEW

**Comment by ericseppanen** [comment]
Also, a style question: should transcripts for episodes that are composed of two or three separate interviews have a way to better distinguish the interviews?
- A title/header at the start of each?
- Links to each section at the top to jump right to the second or third interview?

**Comment by jonhoo** [comment]
I think both of those suggestions are reasonable and desirable!

**Comment by ericseppanen** [comment]
I'll try out some formatting (not sure what markdown allows for internal links), and send a separate PR because this would be applied to a bunch of transcripts.

**Comment by ericseppanen** [comment]
That is true.  As far as I can tell, it's Kramdown doing all the work; I get exactly the same rendering running jekyll in a docker container.  I think I have it working pretty well-- expect another PR for review in the next day or so.

**Pull request merged**
