### PR TITLE
add transcript for episode 030

### PR DESCRIPTION
**Pull request by ericseppanen**
An informative and well-recorded episode.  Thanks @jeremyjung and @thomastaylor312!

### CODE REVIEW

**Comment by ericseppanen** [comment]
The CI failure appears to be a bug in the test: there is a trailing space after the title in _episodes/030-krustlet.md that is breaking the check.

**Review by jonhoo — APPROVED** [review]

**Comment by jonhoo** [comment]
Yeah, the test is pretty dumb — it expects the lines to be literally identical :p

**Comment by ericseppanen** [comment]
I think, weighing the two options:
- fix the test to intelligently strip whitespace, or
- fix the affected files whenever this glitch happens

... the latter is probably easier and keeps the test code simple.

**Comment by jonhoo** [comment]
I agree — let's keep it as-is.

**Pull request merged**
