### PR TITLE
twir 350: transcribe interviews

### PR DESCRIPTION
**Pull request by ericseppanen**
Add transcriptions for the three interviews in TWIR 350.

I also added a Table of Contents so the individual interviews are linked from the top.  These are short interviews so I'm on the fence whether this is really needed...

### CODE REVIEW

**Comment by ericseppanen** [comment]
This is a follow-up to PR #71, cc @nellshamrell.

**Comment by jonhoo** [comment]
Thanks Eric! I'll leave +1-ing to @nellshamrell

**Comment by nellshamrell** [comment]
It looks FANTASTIC! Thank you so much!

**Comment by ericseppanen** [comment]
Thanks for doing these interviews!  They reminded me to sign up for RustConf (my first).

**Pull request merged**
