### PR TITLE
Episode 014 transcript

### PR DESCRIPTION
**Pull request by ericseppanen**
I think the transcript is in pretty good shape, editorially.  See the commit message for more on that.

A few loose ends:
- The CSS style for `inline code` is not great-- on Firefox I get a 12-point font for code and a 16-point font for the rest of the transcript.  Do we want to copy the Rust book style (gray background, padding, border-radius)?
- I notice that the html for `inline code` is very verbose, e.g.
```
<code class="language-plaintext highlighter-rouge">Option</code>
```
It's not a functionality issue, but there doesn't seem to be any corresponding css (or js) that depends on those names.
- For the audio at 11:01 I wrote `[a, b@_, c]`-- is that correct?  I haven't used @-patterns so I'm a little unsure if I was getting that right.
- I have a python script to help extract the text from the json file that aws translate returns.  I also have a  "vocabulary" file that makes aws better handle some of the common rust terms.  Should I check those in to this repo?  If so, where?

### CODE REVIEW

**Comment by jonhoo** [comment]
This is excellent, and I agree with the commit message.

As for your specific points:

 - I agree that fixing up the inline code style is a good idea.
 - We unfortunately can't easily affect the generated code — that is implemented by the markdown transpiler, which we do not control on GitHub pages.
 - Yes, that works, though that would _only_ match three-element slices. The new syntax for matching "arbitrary elements" is `[a, b @ .., c]`.
 - Yes, that seems like a useful script! I think the root is probably good for now, and then make sure also add it to the Jekyll exclusion list here https://github.com/rustacean-station/rustacean-station.org/blob/8ec8df4fc9a8c18bb6b733c4578cace2cd6d595f/_config.yml#L7

**Comment by jonhoo** [comment]
One other question: I wonder if, in transcriptions, we want to make the name of the speaker a little clearer. Maybe bold instead of italics? We can also use custom styling just on the transcription page should we wish. Thoughts?

**Comment by ericseppanen** [comment]
>     * Yes, that works, though that would _only_ match three-element slices. The new syntax for matching "arbitrary elements" is `[a, b @ .., c]`.

What ben says at 11:01 is "bracket A comma B at underscore comma C", so I don't think he meant that-- he calls this the "semantically useless" example :)

**Comment by jonhoo** [comment]
Perfect, yes, then you code transcription is accurate!

**Comment by ericseppanen** [comment]
> One other question: I wonder if, in transcriptions, we want to make the name of the speaker a little clearer. Maybe bold instead of italics? We can also use custom styling just on the transcription page should we wish. Thoughts?

I don't have an opinion on this. It's easy to search-replace in the markdown and use `**Name**` instead.

If we want css rules that apply only to the transcript pages, maybe we want jekyll to emit a different class name, i.e. something different than `<article class="episode full">`?

**Comment by jonhoo** [comment]
> I don't have an opinion on this. It's easy to search-replace in the markdown and use `**Name**` or `__Name__` instead.

Yeah, I think bold would be better looking at it now.

> If we want css rules that apply only to the transcript pages, maybe we want jekyll to emit a different class name, i.e. something different than `<article class="episode full">`?

Oh, yes, that was entirely a mistake on my part. Should just be a matter of changing
https://github.com/rustacean-station/rustacean-station.org/blob/8ec8df4fc9a8c18bb6b733c4578cace2cd6d595f/_layouts/transcript.html#L5

We may want to introduce an additional class for the styling that _should_ be shared between episode and transcriptions though.

**Comment by ericseppanen** [comment]
I added my aws stuff to transcript_tools.  The script is pretty dumb, but in the future could handle everything from upload to polling to fetching the result, etc.

I also added some css to improve the `<code>` styling.  I didn't quite follow what you were saying, whether the article class name will be changing, so this may need adjustment...?

I went and tried a few other browsers, and it looks like only Firefox is rendering the `<code>` blocks in a small font.  Chromium/Linux and Safari/IOS look much better.  I'm not sure why Firefox looks bad, maybe someone else could let me know if Firefox looks bad for them?

**Comment by ericseppanen** [comment]
Looks like the Firefox problem is just due to Firefox having bad defaults.

firefox-is-dumb

I'm guessing there's some way in css to override this default (and all the pages I visit regularly do that).  I haven't figured out what that is, though.

**Comment by ericseppanen** [comment]
FWIW, it looks like it's possible to disable the extra html chatter on `<code>` tags, which makes the transcript html about 8% smaller.

```text
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    span:
      disable : true
```

This leaves the syntax highlighting enabled on code blocks (i.e. markdown ` ``` code here ``` `).

Note for the future: the site currently doesn't appear to have working syntax highlighting.  The html tags are there, but there's no css to do the colors.  If I write `pub enum Foo` inside three-backticks in the markdown, I can see this in the html:
```
<span class="k">pub</span> <span class="k">enum</span> <span class="n">Foo</span>
```

**Comment by jonhoo** [comment]
>  I didn't quite follow what you were saying, whether the article class name will be changing, so this may need adjustment...?

Ah, sorry, let me try to clarify. Yes, I think the class should be changed. Specifically, in the layout for transcripts, the `episode` class should be changed to `transcript`. I think we will also want to add a new class, something like `single`, which we use for any styles that are common between `.episode` and `.transcript`.

> I'm guessing there's some way in css to override this default (and all the pages I visit regularly do that). I haven't figured out what that is, though.

Yeah, this is probably because we don't currently set font sizes anywhere I believe, precisely to respect user defaults. In the case of inline `code` though, that looks pretty bad as you observed. The easiest way to do that is probably to just add `font-size: 100%` to the style for inline `code` tags. I _think_ that should be enough to make Firefox use the regular font size rather than the code font size.

> It looks like it's possible to disable the extra html chatter on `<code>` tags, which makes the transcript html about 8% smaller.

Looks great to me. Let's keep it!

> Note for the future: the site currently doesn't appear to have working syntax highlighting.

Yeah, this is just a matter of including the right rogue (highlighter) CSS sheet. At the same time, maybe we should turn off syntax highlighting entirely in the markdown? We basically don't use it at all, and I think even in transcripts there will be pretty close to no long code samples. What do you think?

**Comment by ericseppanen** [comment]
> > I'm guessing there's some way in css to override this default (and all the pages I visit regularly do that). I haven't figured out what that is, though.
> 
> Yeah, this is probably because we don't currently set font sizes anywhere I believe, precisely to respect user defaults. In the case of inline `code` though, that looks pretty bad as you observed. The easiest way to do that is probably to just add `font-size: 100%` to the style for inline `code` tags. I _think_ that should be enough to make Firefox use the regular font size rather than the code font size.

I tried that, and a few other variations on that. I also tried the [mysterious](http://code.iamkate.com/html-and-css/fixing-browsers-broken-monospace-font-handling/) `font-family:monospace,monospace;` trick, and basically everything that fixes Firefox makes the font too big on Safari.  I got a bit frustrated and decided to set it aside for a bit.

> > Note for the future: the site currently doesn't appear to have working syntax highlighting.
> 
> Yeah, this is just a matter of including the right rogue (highlighter) CSS sheet. At the same time, maybe we should turn off syntax highlighting entirely in the markdown? We basically don't use it at all, and I think even in transcripts there will be pretty close to no long code samples. What do you think?

I don't have an opinion-- as long as nobody uses ` ``` `, leaving syntax-highlighting enabled for "code blocks" doesn't cost anything.  If you'd prefer, I can push a commit that disables it everywhere, and mention in the commit message how to re-enable it for multiline code blocks.

**Comment by ericseppanen** [comment]
> Yes, I think the class should be changed. Specifically, in the layout for transcripts, the `episode` class should be changed to `transcript`. I think we will also want to add a new class, something like `single`, which we use for any styles that are common between `.episode` and `.transcript`.

How about this idea?

- Leave the index page as-is, with multiple `<article class="episode">`
- Leave the existing episode pages as-is, with one big `<article class="episode full">`
- Change the transcript pages to have one big `<article class="episode transcript">`

Then most of the existing css will work fine-- css that refers to `episode` will cover all three, and anything that needs to be specialized can target the more specific name, i.e.
```
.episode.transcript .body code {
    background-color: #f1f1f1;
    padding: 0.1em 0.2em;
}
```
is all that's needed to improve the code style on the transcript pages.

It's a 5-line diff, with no risk of me trying to refactor things and messing them up :)

**Comment by jonhoo** [comment]
> I tried that, and a few other variations on that. I also tried the [mysterious](http://code.iamkate.com/html-and-css/fixing-browsers-broken-monospace-font-handling/) `font-family:monospace,monospace;` trick, and basically everything that fixes Firefox makes the font too big on Safari. I got a bit frustrated and decided to set it aside for a bit.

Fascinating... Yeah, that same trick is also mentioned elsewhere. My read of it is that you need _both_ that `font-family` _and_ `font-size` set somewhere in the document (which I don't know that we do), but I might be wrong. I think just leaving it for now is also fine.

> I don't have an opinion-- as long as nobody uses `` ``` ``, leaving syntax-highlighting enabled for "code blocks" doesn't cost anything. If you'd prefer, I can push a commit that disables it everywhere, and mention in the commit message how to re-enable it for multiline code blocks.

I think my preference would be to disable it, since it won't work right anyway.

> How about this idea?

Seems great to me!

**Comment by jonhoo** [comment]
I went ahead and merged this. Disabling syntax highlighting and possible Firefox CSS fixes we can do in other PRs.

**Comment by ericseppanen** [comment]
The version you merged did have the "disable syntax highlighting everywhere" commit.  So the only loose end from this PR is the bad Firefox <code> default behavior.

**Pull request merged**
