### PR TITLE
Fix listing in two interviews

### PR DESCRIPTION
**Pull request by Philippe-Cholet**
Hi, I appreciate the podcasts. I here fix two listings.

I also noted some broken timestamps in the episodes below but I'm not sure why!
- https://rustacean-station.org/episode/twir-444/
- https://rustacean-station.org/episode/twir-445/
- https://rustacean-station.org/episode/twir-446/

### CODE REVIEW

**Review by jonhoo — APPROVED** [review]

**Comment by jonhoo** [comment]
Thank you!

**Comment by jonhoo** [comment]
For the ones you linked, I think it might be the empty lines between the list items?

**Comment by Philippe-Cholet** [comment]
I had a similar thought so I just removed the said empty lines. Not sure it's good but I don't see what else could cause this.

**Comment by Philippe-Cholet** [comment]
I just checked all five pages render well.

**Comment by jonhoo** [comment]
We should really have a CI step that checks for correct list formatting given how often we get it wrong! Should be doable with a not-too-complicated bash script I think.

**Comment by Philippe-Cholet** [comment]
A rendered html page should not contain `[@`, I think it address both issues here.

**Pull request merged**
